export var plateData = [{
    "text": "京",
    "value": "京",
    "children": [{
        "text": "京A",
        "value": "京A"
    }, {
        "text": "京B",
        "value": "京B"
    }, {
        "text": "京C",
        "value": "京C"
    }, {
        "text": "京D",
        "value": "京D"
    }, {
        "text": "京E",
        "value": "京E"
    }, {
        "text": "京F",
        "value": "京F"
    }, {
        "text": "京G",
        "value": "京G"
    }, {
        "text": "京H",
        "value": "京H"
    }, {
        "text": "京J",
        "value": "京J"
    }, {
        "text": "京K",
        "value": "京K"
    }, {
        "text": "京L",
        "value": "京L"
    }, {
        "text": "京M",
        "value": "京M"
    }, {
        "text": "京Y",
        "value": "京Y"
    }]
}, {
    "text": "沪",
    "value": "沪",
    "children": [{
        "text": "沪A",
        "value": "沪A"
    }, {
        "text": "沪B",
        "value": "沪B"
    }, {
        "text": "沪C",
        "value": "沪C"
    }, {
        "text": "沪D",
        "value": "沪D"
    }, {
        "text": "沪R",
        "value": "沪R"
    }, {
        "text": "沪F",
        "value": "沪F"
    }]
}, {
    "text": "冀",
    "value": "冀",
    "children": [{
        "text": "冀A",
        "value": "冀A"
    }, {
        "text": "冀B",
        "value": "冀B"
    }, {
        "text": "冀C",
        "value": "冀C"
    }, {
        "text": "冀D",
        "value": "冀D"
    }, {
        "text": "冀E",
        "value": "冀E"
    }, {
        "text": "冀F",
        "value": "冀F"
    }, {
        "text": "冀G",
        "value": "冀G"
    }, {
        "text": "冀H",
        "value": "冀H"
    }, {
        "text": "冀J",
        "value": "冀J"
    }, {
        "text": "冀R",
        "value": "冀R"
    }, {
        "text": "冀S",
        "value": "冀S"
    }, {
        "text": "冀T",
        "value": "冀T"
    }, ]
}, {
    "text": "辽",
    "value": "辽",
    "children": [{
        "text": "辽A",
        "value": "辽A"
    }, {
        "text": "辽B",
        "value": "辽B"
    }, {
        "text": "辽C",
        "value": "辽C"
    }, {
        "text": "辽D",
        "value": "辽D"
    }, {
        "text": "辽E",
        "value": "辽E"
    }, {
        "text": "辽F",
        "value": "辽F"
    }, {
        "text": "辽G",
        "value": "辽G"
    }, {
        "text": "辽H",
        "value": "辽H"
    }, {
        "text": "辽J",
        "value": "辽J"
    }, {
        "text": "辽K",
        "value": "辽K"
    }, {
        "text": "辽L",
        "value": "辽L"
    }, {
        "text": "辽M",
        "value": "辽M"
    }, , {
        "text": "辽N",
        "value": "辽N"
    }, {
        "text": "辽P",
        "value": "辽P"
    }]
}, {
    "text": "皖",
    "value": "皖",
    "children": [{
        "text": "皖A",
        "value": "皖A"
    }, {
        "text": "皖B",
        "value": "皖B"
    }, {
        "text": "皖C",
        "value": "皖C"
    }, {
        "text": "皖D",
        "value": "皖D"
    }, {
        "text": "皖E",
        "value": "皖E"
    }, {
        "text": "皖F",
        "value": "皖F"
    }, {
        "text": "皖G",
        "value": "皖G"
    }, {
        "text": "皖H",
        "value": "皖H"
    }, {
        "text": "皖J",
        "value": "皖J"
    }, {
        "text": "皖K",
        "value": "皖K"
    }, {
        "text": "皖L",
        "value": "皖L"
    }, {
        "text": "皖M",
        "value": "皖M"
    }, {
        "text": "皖N",
        "value": "皖N"
    }, {
        "text": "皖P",
        "value": "皖P"
    }, {
        "text": "皖Q",
        "value": "皖Q"
    }, {
        "text": "皖R",
        "value": "皖R"
    }, {
        "text": "皖S",
        "value": "皖S"
    }]
}, {
    "text": "苏",
    "value": "苏",
    "children": [{
        "text": "苏A",
        "value": "苏A"
    }, {
        "text": "苏B",
        "value": "苏B"
    }, {
        "text": "苏C",
        "value": "苏C"
    }, {
        "text": "苏D",
        "value": "苏D"
    }, {
        "text": "苏E",
        "value": "苏E"
    }, {
        "text": "苏F",
        "value": "苏F"
    }, {
        "text": "苏G",
        "value": "苏G"
    }, {
        "text": "苏H",
        "value": "苏H"
    }, {
        "text": "苏J",
        "value": "苏J"
    }, {
        "text": "苏K",
        "value": "苏K"
    }, {
        "text": "苏L",
        "value": "苏L"
    }, {
        "text": "苏M",
        "value": "苏M"
    }, {
        "text": "苏N",
        "value": "苏N"
    }]
}, {
    "text": "鄂",
    "value": "鄂",
    "children": [{
        "text": "鄂A",
        "value": "鄂A"
    }, {
        "text": "鄂B",
        "value": "鄂B"
    }, {
        "text": "鄂C",
        "value": "鄂C"
    }, {
        "text": "鄂D",
        "value": "鄂D"
    }, {
        "text": "鄂E",
        "value": "鄂E"
    }, {
        "text": "鄂F",
        "value": "鄂F"
    }, {
        "text": "鄂G",
        "value": "鄂G"
    }, {
        "text": "鄂H",
        "value": "鄂H"
    }, {
        "text": "鄂J",
        "value": "鄂J"
    }, {
        "text": "鄂K",
        "value": "鄂K"
    }, {
        "text": "鄂L",
        "value": "鄂L"
    }, {
        "text": "鄂M",
        "value": "鄂M"
    }, {
        "text": "鄂N",
        "value": "鄂N"
    }, {
        "text": "鄂R",
        "value": "鄂P"
    }, {
        "text": "鄂Q",
        "value": "鄂Q"
    }, {
        "text": "鄂R",
        "value": "鄂R"
    }, {
        "text": "鄂S",
        "value": "鄂S"
    }]
}, {
    "text": "晋",
    "value": "晋",
    "children": [{
        "text": "晋A",
        "value": "晋A"
    }, {
        "text": "晋B",
        "value": "晋B"
    }, {
        "text": "晋C",
        "value": "晋C"
    }, {
        "text": "晋D",
        "value": "晋D"
    }, {
        "text": "晋E",
        "value": "晋E"
    }, {
        "text": "晋F",
        "value": "晋F"
    }, {
        "text": "晋G",
        "value": "晋G"
    }, {
        "text": "晋H",
        "value": "晋H"
    }, {
        "text": "晋J",
        "value": "晋J"
    }, {
        "text": "晋K",
        "value": "晋K"
    }, {
        "text": "晋L",
        "value": "晋L"
    }, {
        "text": "晋M",
        "value": "晋M"
    }]
}, {
    "text": "吉",
    "value": "吉",
    "children": [{
        "text": "吉A",
        "value": "吉A"
    }, {
        "text": "吉B",
        "value": "吉B"
    }, {
        "text": "吉C",
        "value": "吉C"
    }, {
        "text": "吉D",
        "value": "吉D"
    }, {
        "text": "吉E",
        "value": "吉E"
    }, {
        "text": "吉F",
        "value": "吉F"
    }, {
        "text": "吉G",
        "value": "吉G"
    }, {
        "text": "吉H",
        "value": "吉H"
    }, {
        "text": "吉J",
        "value": "吉J"
    }, {
        "text": "吉K",
        "value": "吉K"
    }]
}, {
    "text": "粤",
    "value": "粤",
    "children": [{
        "text": "粤A",
        "value": "粤A"
    }, {
        "text": "粤B",
        "value": "粤B"
    }, {
        "text": "粤C",
        "value": "粤C"
    }, {
        "text": "粤D",
        "value": "粤D"
    }, {
        "text": "粤E",
        "value": "粤E"
    }, {
        "text": "粤F",
        "value": "粤F"
    }, {
        "text": "粤G",
        "value": "粤G"
    }, {
        "text": "粤H",
        "value": "粤H"
    }, {
        "text": "粤J",
        "value": "粤J"
    }, {
        "text": "粤K",
        "value": "粤K"
    }, {
        "text": "粤L",
        "value": "粤L"
    }, {
        "text": "粤M",
        "value": "粤M"
    }, {
        "text": "粤N",
        "value": "粤N"
    }, {
        "text": "粤P",
        "value": "粤P"
    }, {
        "text": "粤Q",
        "value": "粤Q"
    }, {
        "text": "粤R",
        "value": "粤R"
    }, {
        "text": "粤S",
        "value": "粤S"
    }, {
        "text": "粤T",
        "value": "粤T"
    }, {
        "text": "粤U",
        "value": "粤U"
    }, {
        "text": "粤V",
        "value": "粤V"
    }, {
        "text": "粤W",
        "value": "粤W"
    }, {
        "text": "粤X",
        "value": "粤X"
    }, {
        "text": "粤Y",
        "value": "粤Y"
    }, {
        "text": "粤Z",
        "value": "粤Z"
    }]
}, {
    "text": "宁",
    "value": "宁",
    "children": [{
        "text": "宁A",
        "value": "宁A"
    }, {
        "text": "宁B",
        "value": "宁B"
    }, {
        "text": "宁C",
        "value": "宁C"
    }, {
        "text": "宁D",
        "value": "宁D"
    }, {
        "text": "宁E",
        "value": "宁E"
    }]
}, {
    "text": "豫",
    "value": "豫",
    "children": [{
        "text": "豫A",
        "value": "豫A"
    }, {
        "text": "豫B",
        "value": "豫B"
    }, {
        "text": "豫C",
        "value": "豫C"
    }, {
        "text": "豫D",
        "value": "豫D"
    }, {
        "text": "豫E",
        "value": "豫E"
    }, {
        "text": "豫F",
        "value": "豫F"
    }, {
        "text": "豫G",
        "value": "豫G"
    }, {
        "text": "豫H",
        "value": "豫H"
    }, {
        "text": "豫J",
        "value": "豫J"
    }, {
        "text": "豫K",
        "value": "豫K"
    }, {
        "text": "豫L",
        "value": "豫L"
    }, {
        "text": "豫M",
        "value": "豫M"
    }, {
        "text": "豫N",
        "value": "豫N"
    }, {
        "text": "豫P",
        "value": "豫P"
    }, {
        "text": "豫Q",
        "value": "豫Q"
    }, {
        "text": "豫R",
        "value": "豫R"
    }, {
        "text": "豫S",
        "value": "豫S"
    }, {
        "text": "豫U",
        "value": "豫U"
    }]
}, {
    "text": "黑",
    "value": "黑",
    "children": [{
        "text": "黑A",
        "value": "黑A"
    }, {
        "text": "黑B",
        "value": "黑B"
    }, {
        "text": "黑C",
        "value": "黑C"
    }, {
        "text": "黑D",
        "value": "黑D"
    }, {
        "text": "黑E",
        "value": "黑E"
    }, {
        "text": "黑F",
        "value": "黑F"
    }, {
        "text": "黑G",
        "value": "黑G"
    }, {
        "text": "黑H",
        "value": "黑H"
    }, {
        "text": "黑J",
        "value": "黑J"
    }, {
        "text": "黑K",
        "value": "黑K"
    }, {
        "text": "黑L",
        "value": "黑L"
    }, {
        "text": "黑M",
        "value": "黑M"
    }, {
        "text": "黑N",
        "value": "黑N"
    }, {
        "text": "黑P",
        "value": "黑P"
    }, {
        "text": "黑Q",
        "value": "黑Q"
    }, {
        "text": "黑R",
        "value": "黑R"
    }]
}, {
    "text": "鲁",
    "value": "鲁",
    "children": [{
        "text": "鲁A",
        "value": "鲁A"
    }, {
        "text": "鲁B",
        "value": "鲁B"
    }, {
        "text": "鲁C",
        "value": "鲁C"
    }, {
        "text": "鲁D",
        "value": "鲁D"
    }, {
        "text": "鲁E",
        "value": "鲁E"
    }, {
        "text": "鲁F",
        "value": "鲁F"
    }, {
        "text": "鲁G",
        "value": "鲁G"
    }, {
        "text": "鲁H",
        "value": "鲁H"
    }, {
        "text": "鲁J",
        "value": "鲁J"
    }, {
        "text": "鲁K",
        "value": "鲁K"
    }, {
        "text": "鲁L",
        "value": "鲁L"
    }, {
        "text": "鲁M",
        "value": "鲁M"
    }, {
        "text": "鲁N",
        "value": "鲁N"
    }, {
        "text": "鲁P",
        "value": "鲁P"
    }, {
        "text": "鲁Q",
        "value": "鲁Q"
    }, {
        "text": "鲁R",
        "value": "鲁R"
    }, {
        "text": "鲁S",
        "value": "鲁S"
    }, {
        "text": "鲁T",
        "value": "鲁T"
    }, {
        "text": "鲁U",
        "value": "鲁U"
    }, {
        "text": "鲁V",
        "value": "鲁V"
    }, {
        "text": "鲁Y",
        "value": "鲁Y"
    }]
}, {
    "text": "浙",
    "value": "浙",
    "children": [{
        "text": "浙A",
        "value": "浙A"
    }, {
        "text": "浙B",
        "value": "浙B"
    }, {
        "text": "浙C",
        "value": "浙C"
    }, {
        "text": "浙D",
        "value": "浙D"
    }, {
        "text": "浙E",
        "value": "浙E"
    }, {
        "text": "浙F",
        "value": "浙F"
    }, {
        "text": "浙G",
        "value": "浙G"
    }, {
        "text": "浙H",
        "value": "浙H"
    }, {
        "text": "浙J",
        "value": "浙J"
    }, {
        "text": "浙K",
        "value": "浙K"
    }, {
        "text": "浙L",
        "value": "浙L"
    }]
}, {
    "text": "桂",
    "value": "桂",
    "children": [{
        "text": "桂A",
        "value": "桂A"
    }, {
        "text": "桂B",
        "value": "桂B"
    }, {
        "text": "桂C",
        "value": "桂C"
    }, {
        "text": "桂D",
        "value": "桂D"
    }, {
        "text": "桂E",
        "value": "桂E"
    }, {
        "text": "桂F",
        "value": "桂F"
    }, {
        "text": "桂G",
        "value": "桂G"
    }, {
        "text": "桂H",
        "value": "桂H"
    }, {
        "text": "桂J",
        "value": "桂J"
    }, {
        "text": "桂K",
        "value": "桂K"
    }, {
        "text": "桂L",
        "value": "桂L"
    }, {
        "text": "桂M",
        "value": "桂M"
    }, {
        "text": "桂N",
        "value": "桂N"
    }, {
        "text": "桂P",
        "value": "桂P"
    }, {
        "text": "桂Q",
        "value": "桂Q"
    }, {
        "text": "桂R",
        "value": "桂R"
    }]
}, {
    "text": "蒙",
    "value": "蒙",
    "children": [{
        "text": "蒙A",
        "value": "蒙A"
    }, {
        "text": "蒙B",
        "value": "蒙B"
    }, {
        "text": "蒙C",
        "value": "蒙C"
    }, {
        "text": "蒙D",
        "value": "蒙D"
    }, {
        "text": "蒙E",
        "value": "蒙E"
    }, {
        "text": "蒙F",
        "value": "蒙F"
    }, {
        "text": "蒙G",
        "value": "蒙G"
    }, {
        "text": "蒙H",
        "value": "蒙H"
    }, {
        "text": "蒙J",
        "value": "蒙J"
    }, {
        "text": "蒙K",
        "value": "蒙K"
    }, {
        "text": "蒙L",
        "value": "蒙L"
    }, {
        "text": "蒙M",
        "value": "蒙M"
    }]
}, {
    "text": "闽",
    "value": "闽",
    "children": [{
        "text": "闽A",
        "value": "闽A"
    }, {
        "text": "闽B",
        "value": "闽B"
    }, {
        "text": "闽C",
        "value": "闽C"
    }, {
        "text": "闽D",
        "value": "闽D"
    }, {
        "text": "闽E",
        "value": "闽E"
    }, {
        "text": "闽F",
        "value": "闽F"
    }, {
        "text": "闽G",
        "value": "闽G"
    }, {
        "text": "闽H",
        "value": "闽H"
    }, {
        "text": "闽J",
        "value": "闽J"
    }, {
        "text": "闽K",
        "value": "闽K"
    }]
}, {
    "text": "川",
    "value": "川",
    "children": [{
        "text": "川A",
        "value": "川A"
    }, {
        "text": "川B",
        "value": "川B"
    }, {
        "text": "川C",
        "value": "川C"
    }, {
        "text": "川D",
        "value": "川D"
    }, {
        "text": "川E",
        "value": "川E"
    }, {
        "text": "川F",
        "value": "川F"
    }, {
        "text": "川G",
        "value": "川G"
    }, {
        "text": "川H",
        "value": "川H"
    }, {
        "text": "川J",
        "value": "川J"
    }, {
        "text": "川K",
        "value": "川K"
    }, {
        "text": "川L",
        "value": "川L"
    }, {
        "text": "川M",
        "value": "川M"
    }, {
        "text": "川Q",
        "value": "川Q"
    }, {
        "text": "川R",
        "value": "川R"
    }, {
        "text": "川S",
        "value": "川S"
    }, {
        "text": "川T",
        "value": "川T"
    }, {
        "text": "川U",
        "value": "川U"
    }, {
        "text": "川V",
        "value": "川V"
    }, {
        "text": "川W",
        "value": "川W"
    }, {
        "text": "川X",
        "value": "川X"
    }, {
        "text": "川Y",
        "value": "川Y"
    }, {
        "text": "川Z",
        "value": "川Z"
    }]
}, {
    "text": "渝",
    "value": "渝",
    "children": [{
        "text": "渝A",
        "value": "渝A"
    }, {
        "text": "渝B",
        "value": "渝B"
    }, {
        "text": "渝C",
        "value": "渝C"
    }, {
        "text": "渝D",
        "value": "渝D"
    }, {
        "text": "渝E",
        "value": "渝E"
    }, {
        "text": "渝F",
        "value": "渝F"
    }, {
        "text": "渝G",
        "value": "渝G"
    }]
}, {
    "text": "津",
    "value": "津",
    "children": [{
        "text": "津A",
        "value": "津A"
    }, {
        "text": "津B",
        "value": "津B"
    }, {
        "text": "津C",
        "value": "津C"
    }, {
        "text": "津D",
        "value": "津D"
    }, {
        "text": "津E",
        "value": "津E"
    }, {
        "text": "津F",
        "value": "津F"
    }, {
        "text": "津G",
        "value": "津G"
    }, {
        "text": "津H",
        "value": "津H"
    }]
}, {
    "text": "云",
    "value": "云",
    "children": [{
        "text": "云A",
        "value": "云A"
    }, {
        "text": "云A-V",
        "value": "云A-V"
    }, {
        "text": "云B",
        "value": "云B"
    }, {
        "text": "云C",
        "value": "云C"
    }, {
        "text": "云D",
        "value": "云D"
    }, {
        "text": "云E",
        "value": "云E"
    }, {
        "text": "云F",
        "value": "云F"
    }, {
        "text": "云G",
        "value": "云G"
    }, {
        "text": "云H",
        "value": "云H"
    }, {
        "text": "云J",
        "value": "云J"
    }, {
        "text": "云K",
        "value": "云K"
    }, {
        "text": "云L",
        "value": "云L"
    }, {
        "text": "云M",
        "value": "云M"
    }, {
        "text": "云Q",
        "value": "云Q"
    }, {
        "text": "云R",
        "value": "云R"
    }, {
        "text": "云S",
        "value": "云S"
    }]
}, {
    "text": "湘",
    "value": "湘",
    "children": [{
        "text": "湘A",
        "value": "湘A"
    }, {
        "text": "湘B",
        "value": "湘B"
    }, {
        "text": "湘C",
        "value": "湘C"
    }, {
        "text": "湘D",
        "value": "湘D"
    }, {
        "text": "湘E",
        "value": "湘E"
    }, {
        "text": "湘F",
        "value": "湘F"
    }, {
        "text": "湘G",
        "value": "湘G"
    }, {
        "text": "湘H",
        "value": "湘H"
    }, {
        "text": "湘J",
        "value": "湘J"
    }, {
        "text": "湘K",
        "value": "湘K"
    }, {
        "text": "湘U",
        "value": "湘U"
    }]
}, {
    "text": "新",
    "value": "新",
    "children": [{
        "text": "新A",
        "value": "新A"
    }, {
        "text": "新B",
        "value": "新B"
    }, {
        "text": "新C",
        "value": "新C"
    }, {
        "text": "新D",
        "value": "新D"
    }, {
        "text": "新E",
        "value": "新E"
    }, {
        "text": "新F",
        "value": "新F"
    }, {
        "text": "新G",
        "value": "新G"
    }, {
        "text": "新H",
        "value": "新H"
    }, {
        "text": "新J",
        "value": "新J"
    }, {
        "text": "新K",
        "value": "新K"
    }, {
        "text": "新L",
        "value": "新L"
    }, {
        "text": "新M",
        "value": "新M"
    }, {
        "text": "新Q",
        "value": "新Q"
    }, {
        "text": "新R",
        "value": "新R"
    }]
}, {
    "text": "赣",
    "value": "赣",
    "children": [{
        "text": "赣A",
        "value": "赣A"
    }, {
        "text": "赣B",
        "value": "赣B"
    }, {
    	 "text": "赣C",
        "value": "赣C"
    }, {
        "text": "赣D",
        "value": "赣D"
    }, {
        "text": "赣E",
        "value": "赣E"
    }, {
        "text": "赣F",
        "value": "赣F"
    }, {
        "text": "赣G",
        "value": "赣G"
    }, {
        "text": "赣H",
        "value": "赣H"
    }, {
        "text": "赣J",
        "value": "赣J"
    }, {
        "text": "赣K",
        "value": "赣K"
    }, {
        "text": "赣L",
        "value": "赣L"
    }, {
        "text": "赣M",
        "value": "赣M"
    }]
}, {
    "text": "甘",
    "value": "甘",
    "children": [{
        "text": "甘A",
        "value": "甘A"
    }, {
        "text": "甘B",
        "value": "甘B"
    }, {
    	 "text": "甘C",
        "value": "甘C"
    }, {
        "text": "甘D",
        "value": "甘D"
    }, {
        "text": "甘E",
        "value": "甘E"
    }, {
        "text": "甘F",
        "value": "甘F"
    }, {
        "text": "甘G",
        "value": "甘G"
    }, {
        "text": "甘H",
        "value": "甘H"
    }, {
        "text": "甘J",
        "value": "甘J"
    }, {
        "text": "甘K",
        "value": "甘K"
    }, {
        "text": "甘L",
        "value": "甘L"
    }, {
        "text": "甘M",
        "value": "甘M"
    }, {
        "text": "甘N",
        "value": "甘N"
    }, {
        "text": "甘P",
        "value": "甘P"
    }]
}, {
    "text": "陕",
    "value": "陕",
    "children": [{
        "text": "陕A",
        "value": "陕A"
    }, {
        "text": "陕B",
        "value": "陕B"
    }, {
    	 "text": "陕C",
        "value": "陕C"
    }, {
        "text": "陕D",
        "value": "陕D"
    }, {
        "text": "陕E",
        "value": "陕E"
    }, {
        "text": "陕F",
        "value": "陕F"
    }, {
        "text": "陕G",
        "value": "陕G"
    }, {
        "text": "陕H",
        "value": "陕H"
    }, {
        "text": "陕J",
        "value": "陕J"
    }]
}, {
    "text": "贵",
    "value": "贵",
    "children": [{
        "text": "贵A",
        "value": "贵A"
    }, {
        "text": "贵B",
        "value": "贵B"
    }, {
    	 "text": "贵C",
        "value": "贵C"
    }, {
        "text": "贵D",
        "value": "贵D"
    }, {
        "text": "贵E",
        "value": "贵E"
    }, {
        "text": "贵F",
        "value": "贵F"
    }, {
        "text": "贵G",
        "value": "贵G"
    }, {
        "text": "贵H",
        "value": "贵H"
    }, {
        "text": "贵J",
        "value": "贵J"
    }]
}, {
    "text": "青",
    "value": "青",
    "children": [{
        "text": "青A",
        "value": "青A"
    }, {
        "text": "青B",
        "value": "青B"
    }, {
    	 "text": "青C",
        "value": "青C"
    }, {
        "text": "青D",
        "value": "青D"
    }, {
        "text": "青E",
        "value": "青E"
    }, {
        "text": "青F",
        "value": "青F"
    }, {
        "text": "青G",
        "value": "青G"
    }, {
        "text": "青H",
        "value": "青H"
    }]
}, {
    "text": "琼",
    "value": "琼",
    "children": [{
        "text": "琼A",
        "value": "琼A"
    }, {
        "text": "琼B",
        "value": "琼B"
    }, {
        "value": "琼C"
    }, {
        "text": "琼D",
        "value": "琼D"
    }]
}, {
    "text": "藏",
    "value": "藏",
    "children": [{
        "text": "藏A",
        "value": "藏A"
    }, {
        "text": "藏B",
        "value": "藏B"
    }, {
        "text": "藏C",
        "value": "藏C"
    }, {
        "text": "藏D",
        "value": "藏D"
    }, {
        "text": "藏E",
        "value": "藏E"
    }, {
        "text": "藏F",
        "value": "藏F"
    }, {
        "text": "藏G",
        "value": "藏G"
    }, {
        "text": "藏H",
        "value": "藏H"
    }, {
        "text": "藏J",
        "value": "藏J"
    }]
}]
